version: 2.1

jobs:
  generate_synthetic_data:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Scrape Relevant Data
          command: python scrape.py
      - run:
          name: Generate QA Pairs for LLM
          command: python generate.py
      - store_artifacts:
          path: data
          destination: synthetic-data

workflows:
  pipeline:
    jobs:
      - generate_synthetic_data

  scheduled_pipeline:
    triggers:
      - schedule:
          cron: "59 23 * * *"   # Cron to scehdule workflow on 23:59 everyday.
          filters:
            branches:
              only:
                - main
    jobs:
      - generate_synthetic_data